
export const cliCommands = [
  {
    command: "help",
    output: `
Available commands: 
- 'ls': lists files 
- 'whoami': displays current user 
- 'date': shows current date 
- 'clear': clears the terminal
- 'aws ec2 describe-instances': Describes your active EC2 instances.
- 'aws lambda list-functions': Lists your Lambda functions.
- 'aws ecs list-clusters': Lists your ECS clusters.
- 'aws eks list-clusters': Lists your EKS clusters.
- 'gcloud compute instances list': List all Google Compute Engine virtual machine instances.
- 'az vm list': Get the list of virtual machines.
- 'docker ps': Lists all running Docker containers.
- 'docker images': Lists all local Docker images.
- 'kubectl get pods': Lists all pods in the current namespace.
- 'kubectl get services': Lists all services.
(And many more AWS, GCP, Azure, Docker, and kubectl commands...)
`,
  },
  { command: "ls", output: "README.md  app.js  package.json" },
  { command: "whoami", output: "codingworld_user" },
  { command: "date", output: () => new Date().toString() },
  { command: "aws ec2 describe-instances", output: '{"Reservations": []}' },
  { command: "aws lambda list-functions", output: '{"Functions": []}' },
  { command: "aws ecs list-clusters", output: '{"clusterArns": []}' },
  { command: "aws eks list-clusters", output: '{"clusters": []}' },
  { command: "aws elasticbeanstalk describe-applications", output: '{"Applications": []}' },
  { command: "aws apprunner list-services", output: '{"ServiceSummaryList": []}' },
  { command: "aws autoscaling describe-auto-scaling-groups", output: '{"AutoScalingGroups": []}' },
  { command: "aws s3 ls", output: "Your S3 buckets will be listed here." },
  { command: "aws ec2 describe-volumes", output: '{"Volumes": []}' },
  { command: "aws efs describe-file-systems", output: '{"FileSystems": []}' },
  { command: "aws glacier list-vaults", output: '{"VaultList": []}' },
  { command: "aws ec2 describe-vpcs", output: '{"Vpcs": []}' },
  { command: "aws ec2 describe-subnets", output: '{"Subnets": []}' },
  { command: "aws ec2 describe-route-tables", output: '{"RouteTables": []}' },
  { command: "aws ec2 describe-internet-gateways", output: '{"InternetGateways": []}' },
  { command: "aws ec2 describe-nat-gateways", output: '{"NatGateways": []}' },
  { command: "aws ec2 describe-security-groups", output: '{"SecurityGroups": []}' },
  { command: "aws ec2 describe-network-acls", output: '{"NetworkAcls": []}' },
  { command: "aws elbv2 describe-load-balancers", output: '{"LoadBalancers": []}' },
  { command: 'aws route53 list-hosted-zones', output: '{"HostedZones": []}' },
  { command: "aws cloudfront list-distributions", output: '{"DistributionList": {"Items": []}}' },
  { command: 'aws rds describe-db-instances', output: '{"DBInstances": []}' },
  { command: "aws rds describe-db-clusters", output: '{"DBClusters": []}' },
  { command: 'aws dynamodb list-tables', output: '{"TableNames": []}' },
  { command: "aws elasticache describe-cache-clusters", output: '{"CacheClusters": []}' },
  { command: "aws redshift describe-clusters", output: '{"Clusters": []}' },
  { command: "aws iam list-users", output: '{"Users": []}' },
  { command: "aws iam list-roles", output: '{"Roles": []}' },
  { command: "aws kms list-keys", output: '{"Keys": []}' },
  { command: "aws secretsmanager list-secrets", output: '{"SecretList": []}' },
  { command: "aws cognito-idp list-user-pools --max-results 10", output: '{"UserPools": []}' },
  { command: "aws wafv2 list-web-acls --scope CLOUDFRONT", output: '{"WebACLs": []}' },
  { command: "aws shield describe-protection --protection-id some-id", output: 'An error occurred (ResourceNotFoundException) when calling the DescribeProtection operation: Protection not found.' },
  { command: 'aws cloudwatch describe-alarms', output: '{"MetricAlarms": []}' },
  { command: 'aws logs describe-log-groups', output: '{"logGroups": []}' },
  { command: "aws cloudtrail list-trails", output: '{"Trails": []}' },
  { command: "aws xray get-trace-summaries --start-time 1970-01-01T00:00:00Z --end-time 2038-01-19T03:14:07Z", output: '{"TraceSummaries": []}' },
  { command: "aws codecommit list-repositories", output: '{"repositories": []}' },
  { command: "aws codebuild list-projects", output: '{"projects": []}' },
  { command: "aws codedeploy list-applications", output: '{"applications": []}' },
  { command: "aws codepipeline list-pipelines", output: '{"pipelines": []}' },
  { command: 'aws cloudformation list-stacks', output: '{"StackSummaries": []}' },
  { command: "aws ssm describe-instance-information", output: '{"InstanceInformationList": []}' },
  { command: 'aws sns list-topics', output: '{"Topics": []}' },
  { command: 'aws sqs list-queues', output: '{"QueueUrls": []}' },
  { command: "aws ses list-identities", output: '{"Identities": []}' },
  { command: "aws organizations describe-organization", output: 'An error occurred (AWSOrganizationsNotInUseException) when calling the DescribeOrganization operation: Your account is not a member of an organization.' },
  { command: "aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-02-01 --granularity MONTHLY --metrics \"BlendedCost\"", output: '{"ResultsByTime": []}' },
  { command: "aws budgets describe-budgets --account-id 123456789012", output: '{"Budgets": []}' },
  { command: "aws support describe-trusted-advisor-checks --language en", output: '{"checks": []}' },
  { command: "gcloud compute instances list", output: "Listed 0 items." },
  { command: "gcloud storage buckets list", output: "Listed 0 items." },
  { command: "gcloud projects get-iam-policy YOUR_PROJECT_ID", output: `bindings: []\netag: BwX...` },
  { command: 'gcloud functions list', output: 'Listed 0 items.' },
  { command: 'gcloud sql instances list', output: 'Listed 0 items.' },
  { command: 'gcloud container clusters list', output: 'Listed 0 items.' },
  { command: 'gcloud pubsub topics list', output: 'Listed 0 items.' },
  { command: 'bq ls', output: 'Listed 0 items.' },
  { command: "az vm list", output: "[]" },
  { command: "az storage container list", output: "[]" },
  { command: "az ad user list", output: "[]" },
  { command: 'az functionapp list', output: '[]' },
  { command: 'az cosmosdb list', output: '[]' },
  { command: 'az aks list', output: '[]' },
  { command: 'az devops project list', output: '[]' },
  { command: "docker ps", output: `CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES\n` },
  { command: "docker ps -a", output: `CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES\n` },
  { command: "docker images", output: `REPOSITORY   TAG       IMAGE ID   CREATED   SIZE\n` },
  { command: "docker build -t my-app .", output: "Sending build context to Docker daemon... Successfully built..." },
  { command: "docker-compose up", output: `Creating network "my-project_default" with the default driver\nCreating my-project_web_1 ... done` },
  { command: "docker-compose down", output: `Stopping my-project_web_1 ... done\nRemoving my-project_web_1 ... done\nRemoving network my-project_default` },
  { command: 'cat Dockerfile', output: `FROM node:18\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nEXPOSE 3000\nCMD ["npm", "start"]` },
  { command: 'docker volume create my-volume', output: 'my-volume' },
  { command: 'docker volume ls', output: `DRIVER    VOLUME NAME\nlocal     my-volume` },
  { command: 'docker network ls', output: 'NETWORK ID     NAME      DRIVER    SCOPE' },
  { command: 'docker network create my-net', output: 'a1b2c3d4e5f6' },
  { command: "kubectl get pods", output: `NAME          READY   STATUS    RESTARTS   AGE\n` },
  { command: "kubectl get nodes", output: `NAME      STATUS   ROLES    AGE   VERSION\n` },
  { command: "kubectl get deployments", output: "NAME      READY   UP-TO-DATE   AVAILABLE   AGE" },
  { command: "kubectl scale deployment my-app --replicas=3", output: "deployment.apps/my-app scaled" },
  { command: "kubectl get services", output: "NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE" },
  { command: "kubectl expose deployment my-app --port=80 --type=LoadBalancer", output: "service/my-app exposed" },
  { command: 'kubectl get namespaces', output: `NAME              STATUS   AGE\ndefault           Active   1d\nkube-system       Active   1d\nkube-public       Active   1d` },
  { command: 'kubectl create namespace my-namespace', output: 'namespace/my-namespace created' },
  { command: 'kubectl get configmaps', output: 'No resources found in default namespace.' },
  { command: 'kubectl get secrets', output: 'NAME                  TYPE                                  DATA   AGE' },
  { command: 'kubectl get ingress', output: 'No resources found in default namespace.' },
  { command: 'kubectl get pv', output: 'No resources found.' },
  { command: 'kubectl get pvc', output: 'No resources found in default namespace.' },
  { command: 'pwd', output: '/home/user/CodingworldGaurav' },
  { command: 'ls -l', output: `total 8
-rw-r--r-- 1 user user 1024 Jan 1 12:00 README.md
-rwxr-xr-x 1 user user 4096 Jan 1 12:00 app.js` },
  { command: 'ls -a', output: '. .. .git README.md app.js package.json' },
  { command: 'ls -lh', output: `total 8.0K
-rw-r--r-- 1 user user 1.1K Jan 1 12:00 README.md
-rwxr-xr-x 1 user user 4.0K Jan 1 12:00 app.js` },
  { command: 'cd /path', output: 'bash: cd: /path: No such file or directory' },
  { command: 'cd ..', output: '' },
  { command: 'cd ~', output: '' },
  { command: 'tree', output: `.\n├── README.md\n└── app.js\n\n0 directories, 2 files` },
  { command: 'history', output: '1 ls\n2 whoami\n3 date' },
  { command: 'touch file.txt', output: '' },
  { command: 'mkdir folder', output: '' },
  { command: 'mkdir -p a/b/c', output: '' },
  { command: 'cp file.txt copy.txt', output: '' },
  { command: 'cp -r dir1 dir2', output: 'cp: cannot stat \'dir1\': No such file or directory' },
  { command: 'mv old.txt new.txt', output: 'mv: cannot stat \'old.txt\': No such file or directory' },
  { command: 'mv file.txt /path', output: 'mv: cannot move \'file.txt\' to \'/path\': No such file or directory' },
  { command: 'rm file.txt', output: '' },
  { command: 'rm -r folder', output: '' },
  { command: 'rm -rf folder', output: '' },
  { command: 'rmdir emptyfolder', output: 'rmdir: failed to remove \'emptyfolder\': No such file or directory' },
  { command: 'cat file.txt', output: 'Hello, world!' },
  { command: 'tac file.txt', output: 'Hello, world!' },
  { command: 'less file.txt', output: 'file.txt' },
  { command: 'more file.txt', output: 'file.txt' },
  { command: 'head file.txt', output: 'Hello, world!' },
  { command: 'head -n 20 file.txt', output: 'Hello, world!' },
  { command: 'tail file.txt', output: 'Hello, world!' },
  { command: 'tail -f logs.txt', output: '...' },
  { command: 'nl file.txt', output: '     1\tHello, world!' },
  { command: 'nano file.txt', output: '...' },
  { command: 'vi file.txt', output: '...' },
  { command: 'vim file.txt', output: '...' },
  { command: 'echo "Hello" > file.txt', output: '' },
  { command: 'echo "World" >> file.txt', output: '' },
  { command: 'wc file.txt', output: ' 1  2 12 file.txt' },
  { command: 'wc -l file.txt', output: '1 file.txt' },
  { command: 'sort file.txt', output: 'Hello\nWorld' },
  { command: 'uniq file.txt', output: 'Hello\nWorld' },
  { command: 'grep "word" file.txt', output: '' },
  { command: 'grep -i "word" file.txt', output: '' },
  { command: 'grep -r "text" .', output: '' },
  { command: 'find / -name file.txt', output: '/home/user/CodingworldGaurav/file.txt' },
  { command: 'find . -type f', output: './README.md\n./app.js\n./file.txt' },
  { command: 'cut -d " " -f1 file.txt', output: 'Hello\n' },
  { command: 'awk \'{print $1}\' file.txt', output: 'Hello\n' },
  { command: 'sed \'s/old/new/\' file.txt', output: 'Hellow\n' },
  { command: 'chmod 777 file.txt', output: '' },
  { command: 'chmod 755 script.sh', output: 'chmod: cannot access \'script.sh\': No such file or directory' },
  { command: 'chmod +x script.sh', output: 'chmod: cannot access \'script.sh\': No such file or directory' },
  { command: 'chown user file.txt', output: '' },
  { command: 'chown user:group file.txt', output: '' },
  { command: 'umask', output: '0022' },
  { command: 'who', output: 'user     pts/0        2024-01-01 12:00' },
  { command: 'id', output: 'uid=1000(user) gid=1000(user) groups=1000(user)' },
  { command: 'adduser username', output: 'adduser: The user `username\' already exists.' },
  { command: 'userdel username', output: 'userdel: user username is currently used by process 1234' },
  { command: 'groupadd groupname', output: 'groupadd: group \'groupname\' already exists' },
  { command: 'passwd username', output: 'Changing password for username.\n(current) UNIX password:' },
  { command: 'su username', output: 'Password: ' },
  { command: 'sudo command', output: '[sudo] password for user: ' },
  { command: 'ps', output: '  PID TTY          TIME CMD\n 1234 pts/0    00:00:00 bash\n 5678 pts/0    00:00:00 ps' },
  { command: 'ps aux', output: 'USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND\nroot           1  0.0  0.0 168920  8864 ?        Ss   Jan01   0:01 /sbin/init\nuser        1234  0.0  0.0  13372  3984 pts/0    Ss   12:00   0:00 -bash' },
  { command: 'top', output: 'top - 12:00:00 up 1 day,  2:00,  1 user,  load average: 0.00, 0.01, 0.05\nTasks:   1 total,   1 running,   0 sleeping,   0 stopped,   0 zombie' },
  { command: 'htop', output: 'htop: command not found' },
  { command: 'kill 1234', output: '' },
  { command: 'kill -9 1234', output: '' },
  { command: 'pkill processname', output: '' },
  { command: 'bg', output: 'bash: bg: current: no such job' },
  { command: 'fg', output: 'bash: fg: current: no such job' },
  { command: 'jobs', output: '' },
  { command: 'nohup command &', output: '[1] 12345' },
  { command: 'ip a', output: '1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000\n    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00\n    inet 127.0.0.1/8 scope host lo\n       valid_lft forever preferred_lft forever\n' },
  { command: 'ifconfig', output: 'eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500\n        inet 172.17.0.2  netmask 255.255.0.0  broadcast 172.17.255.255' },
  { command: 'ping google.com', output: 'PING google.com (142.250.179.206) 56(84) bytes of data.\n64 bytes from lhr4s01-in-f14.1e100.net (142.250.179.206): icmp_seq=1 ttl=118 time=11.1 ms' },
  { command: 'curl http://example.com', output: '<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n...</' },
  { command: 'wget http://example.com/file', output: 'wget: unable to resolve host address ‘example.com’' },
  { command: 'netstat -tulnp', output: '(Not all processes could be identified, non-owned process info\n will not be shown, you would have to be root to see it all.)\nActive Internet connections (only servers)' },
  { command: 'ss -tulnp', output: 'Netid  State   Recv-Q  Send-Q    Local Address:Port   Peer Address:Port Process' },
  { command: 'ssh user@ip', output: 'ssh: connect to host ip port 22: Connection refused' },
  { command: 'scp file user@ip:/path', output: 'ssh: connect to host ip port 22: Connection refused' },
  { command: 'df -h', output: 'Filesystem      Size  Used Avail Use% Mounted on\n/dev/vda1        25G   10G   15G  40% /' },
  { command: 'du -sh *', output: '4.0K\tREADME.md\n4.0K\tapp.js' },
  { command: 'free -m', output: '              total        used        free      shared  buff/cache   available\nMem:           7963         838        6549           0         575        6827\nSwap:             0           0           0' },
  { command: 'uptime', output: ' 12:00:00 up 1 day,  2:00,  1 user,  load average: 0.00, 0.01, 0.05' },
  { command: 'uname -a', output: 'Linux codingworld 5.4.0-1029-gcp #31~18.04.1-Ubuntu SMP Tue Oct 20 16:11:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux' },
  { command: 'hostname', output: 'codingworld' },
  { command: 'lsblk', output: 'NAME  MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT\nvda   254:0    0   25G  0 disk /\n' },
  { command: 'mount', output: '/dev/vda1 on / type ext4 (rw,relatime,discard)' },
  { command: 'umount', output: 'umount: /: target is busy.' },
  { command: 'apt update', output: 'Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease\nGet:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]' },
  { command: 'apt upgrade', output: '0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.' },
  { command: 'apt install nginx', output: 'The following additional packages will be installed:\n  nginx-common nginx-core\n0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.' },
  { command: 'apt remove nginx', output: 'The following packages will be REMOVED:\n  nginx nginx-common nginx-core\n0 to upgrade, 0 to newly install, 3 to remove and 0 not upgraded.' },
  { command: 'dpkg -l', output: 'Desired=Unknown/Install/Remove/Purge/Hold\n| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend\n|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)' },
  { command: 'yum install nginx', output: 'yum: command not found' },
  { command: 'yum update', output: 'yum: command not found' },
  { command: 'tar -cvf file.tar folder', output: 'tar: folder: Cannot stat: No such file or directory\ntar: Exiting with failure status due to previous errors.' },
  { command: 'tar -xvf file.tar', output: 'tar: file.tar: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now' },
  { command: 'tar -czvf file.tar.gz folder', output: 'tar: folder: Cannot stat: No such file or directory\ntar: Exiting with failure status due to previous errors.' },
  { command: 'tar -xzvf file.tar.gz', output: 'tar: file.tar.gz: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now' },
  { command: 'zip file.zip file.txt', output: '  adding: file.txt (deflated 13%)' },
  { command: 'unzip file.zip', output: 'Archive:  file.zip\n  inflating: file.txt' },
  { command: 'crontab -l', output: 'no crontab for user' },
  { command: 'crontab -e', output: 'no crontab for user - using an empty one' },
  { command: 'dmesg', output: '[    0.000000] Linux version 5.4.0-1029-gcp (...' },
  { command: 'journalctl', output: '-- Logs begin at ... --' },
  { command: 'journalctl -u nginx', output: '-- No entries --' },
  { command: 'tail -f /var/log/syslog', output: '...' },
  { command: 'env', output: '...' },
  { command: 'printenv', output: '...' },
  { command: 'export VAR=value', output: '' },
  { command: 'echo $VAR', output: 'value' },
  { command: 'ls > files.txt', output: '' },
  { command: 'ls >> files.txt', output: '' },
  { command: 'cat file.txt | grep word', output: '' },
  { command: 'ps aux | grep nginx', output: '' },
  { command: 'sort file.txt | uniq', output: 'Hello\nWorld' },
  { command: 'which python', output: '/usr/bin/python' },
  { command: 'whereis nginx', output: 'nginx:' },
  { command: 'alias ll=\'ls -la\'', output: '' },
  { command: 'reboot', output: 'Rebooting.' },
  { command: 'shutdown now', output: 'Shutdown scheduled for ...' },
];
