export const cliCommands = [
  {
    command: "help",
    output: `
Available commands: 
- 'ls': lists files 
- 'whoami': displays current user 
- 'date': shows current date 
- 'clear': clears the terminal
- 'aws ec2 describe-instances': Describes your active EC2 instances.
- 'aws lambda list-functions': Lists your Lambda functions.
- 'aws ecs list-clusters': Lists your ECS clusters.
- 'aws eks list-clusters': Lists your EKS clusters.
- 'gcloud compute instances list': List all Google Compute Engine virtual machine instances.
- 'az vm list': Get the list of virtual machines.
- 'docker ps': Lists all running Docker containers.
- 'docker images': Lists all local Docker images.
- 'kubectl get pods': Lists all pods in the current namespace.
- 'kubectl get services': Lists all services.
(And many more AWS, GCP, Azure, Docker, and kubectl commands...)
`,
  },
  { command: "ls", output: "README.md  app.js  package.json" },
  { command: "whoami", output: "codingworld_user" },
  { command: "date", output: () => new Date().toString() },
  { command: "aws ec2 describe-instances", output: '{"Reservations": []}' },
  { command: "aws lambda list-functions", output: '{"Functions": []}' },
  { command: "aws ecs list-clusters", output: '{"clusterArns": []}' },
  { command: "aws eks list-clusters", output: '{"clusters": []}' },
  { command: "aws elasticbeanstalk describe-applications", output: '{"Applications": []}' },
  { command: "aws apprunner list-services", output: '{"ServiceSummaryList": []}' },
  { command: "aws autoscaling describe-auto-scaling-groups", output: '{"AutoScalingGroups": []}' },
  { command: "aws s3 ls", output: "Your S3 buckets will be listed here." },
  { command: "aws ec2 describe-volumes", output: '{"Volumes": []}' },
  { command: "aws efs describe-file-systems", output: '{"FileSystems": []}' },
  { command: "aws glacier list-vaults", output: '{"VaultList": []}' },
  { command: "aws ec2 describe-vpcs", output: '{"Vpcs": []}' },
  { command: "aws ec2 describe-subnets", output: '{"Subnets": []}' },
  { command: "aws ec2 describe-route-tables", output: '{"RouteTables": []}' },
  { command: "aws ec2 describe-internet-gateways", output: '{"InternetGateways": []}' },
  { command: "aws ec2 describe-nat-gateways", output: '{"NatGateways": []}' },
  { command: "aws ec2 describe-security-groups", output: '{"SecurityGroups": []}' },
  { command: "aws ec2 describe-network-acls", output: '{"NetworkAcls": []}' },
  { command: "aws elbv2 describe-load-balancers", output: '{"LoadBalancers": []}' },
  { command: 'aws route53 list-hosted-zones', output: '{"HostedZones": []}' },
  { command: "aws cloudfront list-distributions", output: '{"DistributionList": {"Items": []}}' },
  { command: 'aws rds describe-db-instances', output: '{"DBInstances": []}' },
  { command: "aws rds describe-db-clusters", output: '{"DBClusters": []}' },
  { command: 'aws dynamodb list-tables', output: '{"TableNames": []}' },
  { command: "aws elasticache describe-cache-clusters", output: '{"CacheClusters": []}' },
  { command: "aws redshift describe-clusters", output: '{"Clusters": []}' },
  { command: "aws iam list-users", output: '{"Users": []}' },
  { command: "aws iam list-roles", output: '{"Roles": []}' },
  { command: "aws kms list-keys", output: '{"Keys": []}' },
  { command: "aws secretsmanager list-secrets", output: '{"SecretList": []}' },
  { command: "aws cognito-idp list-user-pools --max-results 10", output: '{"UserPools": []}' },
  { command: "aws wafv2 list-web-acls --scope CLOUDFRONT", output: '{"WebACLs": []}' },
  { command: "aws shield describe-protection --protection-id some-id", output: 'An error occurred (ResourceNotFoundException) when calling the DescribeProtection operation: Protection not found.' },
  { command: 'aws cloudwatch describe-alarms', output: '{"MetricAlarms": []}' },
  { command: 'aws logs describe-log-groups', output: '{"logGroups": []}' },
  { command: "aws cloudtrail list-trails", output: '{"Trails": []}' },
  { command: "aws xray get-trace-summaries --start-time 1970-01-01T00:00:00Z --end-time 2038-01-19T03:14:07Z", output: '{"TraceSummaries": []}' },
  { command: "aws codecommit list-repositories", output: '{"repositories": []}' },
  { command: "aws codebuild list-projects", output: '{"projects": []}' },
  { command: "aws codedeploy list-applications", output: '{"applications": []}' },
  { command: "aws codepipeline list-pipelines", output: '{"pipelines": []}' },
  { command: 'aws cloudformation list-stacks', output: '{"StackSummaries": []}' },
  { command: "aws ssm describe-instance-information", output: '{"InstanceInformationList": []}' },
  { command: 'aws sns list-topics', output: '{"Topics": []}' },
  { command: 'aws sqs list-queues', output: '{"QueueUrls": []}' },
  { command: "aws ses list-identities", output: '{"Identities": []}' },
  { command: "aws organizations describe-organization", output: 'An error occurred (AWSOrganizationsNotInUseException) when calling the DescribeOrganization operation: Your account is not a member of an organization.' },
  { command: "aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-02-01 --granularity MONTHLY --metrics \"BlendedCost\"", output: '{"ResultsByTime": []}' },
  { command: "aws budgets describe-budgets --account-id 123456789012", output: '{"Budgets": []}' },
  { command: "aws support describe-trusted-advisor-checks --language en", output: '{"checks": []}' },
  { command: "gcloud compute instances list", output: "Listed 0 items." },
  { command: "gcloud storage buckets list", output: "Listed 0 items." },
  { command: "gcloud projects get-iam-policy YOUR_PROJECT_ID", output: `bindings: []\netag: BwX...` },
  { command: 'gcloud functions list', output: 'Listed 0 items.' },
  { command: 'gcloud sql instances list', output: 'Listed 0 items.' },
  { command: 'gcloud container clusters list', output: 'Listed 0 items.' },
  { command: 'gcloud pubsub topics list', output: 'Listed 0 items.' },
  { command: 'bq ls', output: 'Listed 0 items.' },
  { command: "az vm list", output: "[]" },
  { command: "az storage container list", output: "[]" },
  { command: "az ad user list", output: "[]" },
  { command: 'az functionapp list', output: '[]' },
  { command: 'az cosmosdb list', output: '[]' },
  { command: 'az aks list', output: '[]' },
  { command: 'az devops project list', output: '[]' },
  { command: "docker ps", output: `CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES\n` },
  { command: "docker ps -a", output: `CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES\n` },
  { command: "docker images", output: `REPOSITORY   TAG       IMAGE ID   CREATED   SIZE\n` },
  { command: "docker build -t my-app .", output: "Sending build context to Docker daemon... Successfully built..." },
  { command: "docker-compose up", output: `Creating network "my-project_default" with the default driver\nCreating my-project_web_1 ... done` },
  { command: "docker-compose down", output: `Stopping my-project_web_1 ... done\nRemoving my-project_web_1 ... done\nRemoving network my-project_default` },
  { command: 'cat Dockerfile', output: `FROM node:18\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nEXPOSE 3000\nCMD ["npm", "start"]` },
  { command: 'docker volume create my-volume', output: 'my-volume' },
  { command: 'docker volume ls', output: `DRIVER    VOLUME NAME\nlocal     my-volume` },
  { command: 'docker network ls', output: 'NETWORK ID     NAME      DRIVER    SCOPE' },
  { command: 'docker network create my-net', output: 'a1b2c3d4e5f6' },
  { command: "kubectl get pods", output: `NAME          READY   STATUS    RESTARTS   AGE\n` },
  { command: "kubectl get nodes", output: `NAME      STATUS   ROLES    AGE   VERSION\n` },
  { command: "kubectl get deployments", output: "NAME      READY   UP-TO-DATE   AVAILABLE   AGE" },
  { command: "kubectl scale deployment my-app --replicas=3", output: "deployment.apps/my-app scaled" },
  { command: "kubectl get services", output: "NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE" },
  { command: "kubectl expose deployment my-app --port=80 --type=LoadBalancer", output: "service/my-app exposed" },
  { command: 'kubectl get namespaces', output: `NAME              STATUS   AGE\ndefault           Active   1d\nkube-system       Active   1d\nkube-public       Active   1d` },
  { command: 'kubectl create namespace my-namespace', output: 'namespace/my-namespace created' },
  { command: 'kubectl get configmaps', output: 'No resources found in default namespace.' },
  { command: 'kubectl get secrets', output: 'NAME                  TYPE                                  DATA   AGE' },
  { command: 'kubectl get ingress', output: 'No resources found in default namespace.' },
  { command: 'kubectl get pv', output: 'No resources found.' },
  { command: 'kubectl get pvc', output: 'No resources found in default namespace.' },
];
