
export const allCommands = [
  "help",
  "ls",
  "whoami",
  "date",
  "clear",
  "aws ec2 describe-instances",
  "aws lambda list-functions",
  "aws ecs list-clusters",
  "aws eks list-clusters",
  "gcloud compute instances list",
  "az vm list",
  "docker ps",
  "docker images",
  "kubectl get pods",
  "kubectl get services",
  "aws elasticbeanstalk describe-applications",
  "aws apprunner list-services",
  "aws autoscaling describe-auto-scaling-groups",
  "aws s3 ls",
  "aws ec2 describe-volumes",
  "aws efs describe-file-systems",
  "aws glacier list-vaults",
  "aws ec2 describe-vpcs",
  "aws ec2 describe-subnets",
  "aws ec2 describe-route-tables",
  "aws ec2 describe-internet-gateways",
  "aws ec2 describe-nat-gateways",
  "aws ec2 describe-security-groups",
  "aws ec2 describe-network-acls",
  "aws elbv2 describe-load-balancers",
  "aws route53 list-hosted-zones",
  "aws cloudfront list-distributions",
  "aws rds describe-db-instances",
  "aws rds describe-db-clusters",
  "aws dynamodb list-tables",
  "aws elasticache describe-cache-clusters",
  "aws redshift describe-clusters",
  "aws iam list-users",
  "aws iam list-roles",
  "aws kms list-keys",
  "aws secretsmanager list-secrets",
  "aws cognito-idp list-user-pools --max-results 10",
  "aws wafv2 list-web-acls --scope CLOUDFRONT",
  "aws shield describe-protection --protection-id some-id",
  "aws cloudwatch describe-alarms",
  "aws logs describe-log-groups",
  "aws cloudtrail list-trails",
  "aws xray get-trace-summaries --start-time 1970-01-01T00:00:00Z --end-time 2038-01-19T03:14:07Z",
  "aws codecommit list-repositories",
  "aws codebuild list-projects",
  "aws codedeploy list-applications",
  "aws codepipeline list-pipelines",
  "aws cloudformation list-stacks",
  "aws ssm describe-instance-information",
  "aws sns list-topics",
  "aws sqs list-queues",
  "aws ses list-identities",
  "aws organizations describe-organization",
  "aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-02-01 --granularity MONTHLY --metrics \"BlendedCost\"",
  "aws budgets describe-budgets --account-id 123456789012",
  "aws support describe-trusted-advisor-checks --language en",
  "gcloud compute instances list",
  "gcloud storage buckets list",
  "gcloud projects get-iam-policy YOUR_PROJECT_ID",
  "gcloud functions list",
  "gcloud sql instances list",
  "gcloud container clusters list",
  "gcloud pubsub topics list",
  "bq ls",
  "az vm list",
  "az storage container list",
  "az ad user list",
  "az functionapp list",
  "az cosmosdb list",
  "az aks list",
  "az devops project list",
  "docker ps",
  "docker ps -a",
  "docker images",
  "docker build -t my-app .",
  "docker-compose up",
  "docker-compose down",
  "cat Dockerfile",
  "docker volume create my-volume",
  "docker volume ls",
  "docker network ls",
  "docker network create my-net",
  "kubectl get pods",
  "kubectl get nodes",
  "kubectl get deployments",
  "kubectl scale deployment my-app --replicas=3",
  "kubectl get services",
  "kubectl expose deployment my-app --port=80 --type=LoadBalancer",
  "kubectl get namespaces",
  "kubectl create namespace my-namespace",
  "kubectl get configmaps",
  "kubectl get secrets",
  "kubectl get ingress",
  "kubectl get pv",
  "kubectl get pvc",
  "pwd",
  "ls -l",
  "ls -a",
  "ls -lh",
  "cd /path",
  "cd ..",
  "cd ~",
  "tree",
  "history",
  "touch file.txt",
  "mkdir folder",
  "mkdir -p a/b/c",
  "cp file.txt copy.txt",
  "cp -r dir1 dir2",
  "mv old.txt new.txt",
  "mv file.txt /path",
  "rm file.txt",
  "rm -r folder",
  "rm -rf folder",
  "rmdir emptyfolder",
  "cat file.txt",
  "tac file.txt",
  "less file.txt",
  "more file.txt",
  "head file.txt",
  "head -n 20 file.txt",
  "tail file.txt",
  "tail -f logs.txt",
  "nl file.txt",
  "nano file.txt",
  "vi file.txt",
  "vim file.txt",
  "echo \"Hello\" > file.txt",
  "echo \"World\" >> file.txt",
  "wc file.txt",
  "wc -l file.txt",
  "sort file.txt",
  "uniq file.txt",
  "grep \"word\" file.txt",
  "grep -i \"word\" file.txt",
  "grep -r \"text\" .",
  "find / -name file.txt",
  "find . -type f",
  "cut -d \" \" -f1 file.txt",
  "awk '{print $1}' file.txt",
  "sed 's/old/new/' file.txt",
  "chmod 777 file.txt",
  "chmod 755 script.sh",
  "chmod +x script.sh",
  "chown user file.txt",
  "chown user:group file.txt",
  "umask",
  "who",
  "id",
  "adduser username",
  "userdel username",
  "groupadd groupname",
  "passwd username",
  "su username",
  "sudo command",
  "ps",
  "ps aux",
  "top",
  "htop",
  "kill 1234",
  "kill -9 1234",
  "pkill processname",
  "bg",
  "fg",
  "jobs",
  "nohup command &",
  "ip a",
  "ifconfig",
  "ping google.com",
  "curl http://example.com",
  "wget http://example.com/file",
  "netstat -tulnp",
  "ss -tulnp",
  "ssh user@ip",
  "scp file user@ip:/path",
  "df -h",
  "du -sh *",
  "free -m",
  "uptime",
  "uname -a",
  "hostname",
  "lsblk",
  "mount",
  "umount",
  "apt update",
  "apt upgrade",
  "apt install nginx",
  "apt remove nginx",
  "dpkg -l",
  "yum install nginx",
  "yum update",
  "tar -cvf file.tar folder",
  "tar -xvf file.tar",
  "tar -czvf file.tar.gz folder",
  "tar -xzvf file.tar.gz",
  "zip file.zip file.txt",
  "unzip file.zip",
  "crontab -l",
  "crontab -e",
  "dmesg",
  "journalctl",
  "journalctl -u nginx",
  "tail -f /var/log/syslog",
  "env",
  "printenv",
  "export VAR=value",
  "echo $VAR",
  "ls > files.txt",
  "ls >> files.txt",
  "cat file.txt | grep word",
  "ps aux | grep nginx",
  "sort file.txt | uniq",
  "which python",
  "whereis nginx",
  "alias ll='ls -la'",
  "reboot",
  "shutdown now",
];
